// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"manager/pkg/models/shared"
	"net/http"
)

type DeleteAllCommonIntegrationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Delete all integrations success
	ResponseMessage *shared.ResponseMessage
}
