// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"manager/pkg/models/shared"
	"net/http"
)

type DeleteOneCommonIntegrationRequest struct {
	// Name of integration
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type DeleteOneCommonIntegrationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Delete common integration success response
	ResponseMessage *shared.ResponseMessage
}
