// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"manager/pkg/models/shared"
	"net/http"
)

type GetAllCommonIntegrationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Common integration success response
	CommonIntegrationsObject []shared.CommonIntegrationObject
}
