// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"manager/pkg/models/shared"
	"net/http"
)

type GetOneCommonIntegrationRequest struct {
	// Name of integration
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type GetOneCommonIntegrationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Common integration success response
	CommonIntegrationObject *shared.CommonIntegrationObject
}
