// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"manager/pkg/models/shared"
	"net/http"
)

type PutAllCommonIntegrationRequest struct {
	// Common integration config
	CommonIntegrationObject shared.CommonIntegrationObject `request:"mediaType=application/json"`
	// Name of integration
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type PutAllCommonIntegrationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Common integration update success
	ResponseMessage *shared.ResponseMessage
}
