// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CommonIntegrationObjectSubscriptionsGroups struct {
	Attributes map[string]string `json:"attributes,omitempty"`
	Name       string            `json:"name"`
	Values     map[string]string `json:"values,omitempty"`
}

type CommonIntegrationObjectSubscriptions struct {
	Attributes map[string]string                            `json:"attributes,omitempty"`
	Groups     []CommonIntegrationObjectSubscriptionsGroups `json:"groups,omitempty"`
	Name       string                                       `json:"name"`
}

type CommonIntegrationObjectTarget struct {
	Attributes map[string]string `json:"attributes,omitempty"`
	Name       *string           `json:"name,omitempty"`
}

// CommonIntegrationObject - Common integration config
type CommonIntegrationObject struct {
	Name          string                                 `json:"name"`
	Subscriptions []CommonIntegrationObjectSubscriptions `json:"subscriptions,omitempty"`
	Target        *CommonIntegrationObjectTarget         `json:"target,omitempty"`
}
