// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseMessage - Delete all integrations success
type ResponseMessage struct {
	Message *string `json:"message,omitempty"`
}
